version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: compagny_database
      POSTGRES_USER: dirane
      POSTGRES_PASSWORD: dirane
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network-dirane
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: diraneserges@gmail.com
      PGADMIN_DEFAULT_PASSWORD: test
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres-network-dirane
    ports:
      - "5050:80"
    depends_on:
      - postgres


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    environment:
      RABBITMQ_DEFAULT_USER: dirane
      RABBITMQ_DEFAULT_PASS: dirane
    ports:
      - "5672:5672"  # Port pour les connexions d'applications
      - "15672:15672"  # Port pour l'interface de gestion
    networks:
      - postgres-network-dirane

  eureka-server:
    image: registry-container-image:latest
    container_name: eureka_container
    ports:
      - "8761:8761"
    networks:
      - postgres-network-dirane


networks:
  postgres-network-dirane:
    external: true

volumes:
  postgres_data:
  pgadmin_data:
