version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: compagny_database
      POSTGRES_USER: dirane
      POSTGRES_PASSWORD: dirane
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network-dirane
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: diraneserges@gmail.com
      PGADMIN_DEFAULT_PASSWORD: test
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres-network-dirane
    ports:
      - "5050:80"
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    environment:
      RABBITMQ_DEFAULT_USER: dirane
      RABBITMQ_DEFAULT_PASS: dirane
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - postgres-network-dirane

  eureka-server:
    image: registry-container-image:latest
    container_name: eureka_container
    ports:
      - "8761:8761"
    networks:
      - postgres-network-dirane

  compagny-service:
    image: compagny-container-image:latest
    container_name: compagny_service_container
    ports:
      - "8082:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/compagny_database
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=dirane
      - SPRING_DATASOURCE_PASSWORD=dirane
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=dirane
      - SPRING_RABBITMQ_PASSWORD=dirane
    volumes:
      - h2_data:/data
    depends_on:
      - eureka-server
      - rabbitmq
      - postgres
    networks:
      - postgres-network-dirane

  job-service:
    image: job-container-image:latest
    container_name: job_service_container
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/compagny_database
      - SPRING_DATASOURCE_USERNAME=dirane
      - SPRING_DATASOURCE_PASSWORD=dirane
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=dirane
      - SPRING_RABBITMQ_PASSWORD=dirane
    depends_on:
      - postgres
      - rabbitmq
      - eureka-server
    networks:
      - postgres-network-dirane

networks:
  postgres-network-dirane:
    external: true

volumes:
  postgres_data:
  pgadmin_data:
  h2_data:
